### ISSUE TITLE
Afficher les vidéos v.redd.it

### ISSUE THREAD

**Issue by MrCodeMUN** [href404/discord-bot#10]
# Description

Faire en sorte que les vidéos hébergées sur le site v.redd.it puissent être jouées directement sur le client Discord.

## Comportement actuel
![Sans titre](https://user-images.githubusercontent.com/32191782/130335306-ec83793c-d764-4ace-9870-4ab75729b022.png)

### Comportement n°1
![image](https://user-images.githubusercontent.com/32191782/130335368-e6bb0227-9955-4cb9-8854-14048793829f.png)

**Comment by href404** [comment]
@MrCodeMUN traité lors de la réécriture du bot en TypeScript, je clôture.
